import type { CallDetail, CallSummary, RepDetail, RepSummary } from "./types";

// `||` (not `??`) so an empty-string env var also falls back to the default,
// not just an unset/null one.
const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8000";

async function getJson<T>(path: string): Promise<T> {
  // The seeded demo dataset doesn't change during the process lifetime, so
  // a short revalidate window avoids refetching on every render while still
  // picking up a backend restart within a minute. `next` is a Next.js
  // fetch() extension; its ambient type only resolves once next-env.d.ts
  // exists (auto-generated by `next dev`/`next build`), so cast rather than
  // depend on that file being present for a plain `tsc --noEmit` run.
  const response = await fetch(`${API_BASE_URL}${path}`, {
    next: { revalidate: 60 },
  } as RequestInit);
  if (!response.ok) {
    throw new Error(`Request to ${path} failed with status ${response.status}`);
  }
  return response.json() as Promise<T>;
}

export function fetchReps(): Promise<RepSummary[]> {
  return getJson<RepSummary[]>("/api/reps");
}

export function fetchRep(repId: string): Promise<RepDetail> {
  return getJson<RepDetail>(`/api/reps/${repId}`);
}

export function fetchCalls(): Promise<CallSummary[]> {
  return getJson<CallSummary[]>("/api/calls");
}

export function fetchCall(callId: string): Promise<CallDetail> {
  return getJson<CallDetail>(`/api/calls/${callId}`);
}
